name: Schedule Python Script Execution

on:
  schedule:
    - cron: "0 0-9 * * 1-5" # KST 9시부터 18시까지에 해당하는 UTC 시간 0시부터 9시까지

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-3.12
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip to Latest Version
        run: python -m pip install --upgrade pip

      - name: Install Python Dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Python Script
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID_1: ${{ secrets.TELEGRAM_CHAT_ID_1 }}
          TELEGRAM_CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
          TELEGRAM_CHAT_ID_3: ${{ secrets.TELEGRAM_CHAT_ID_3 }}
          RECODE_GIST_ID: ${{ secrets.RECODE_GIST_ID }}
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGCHAIN_TRACING_V2: ${{ secrets.LANGCHAIN_TRACING_V2 }}
          LANGCHAIN_ENDPOINT: ${{ secrets.LANGCHAIN_ENDPOINT }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
        run: |
          python main.py || echo "main.py failed"
